//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRequest
    {
        public string Request_ID { get; set; }
        public string Customer_ID { get; set; }
        public string Product_ID { get; set; }
        public string Staff_ID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Request_Date { get; set; }
        public string Req_Status { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
