//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRequestHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerRequestHeader()
        {
            this.CustomerRequestDetails = new HashSet<CustomerRequestDetail>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public string Request_ID { get; set; }
        public string Customer_ID { get; set; }
        public string Staff_ID { get; set; }
        public System.DateTime Request_Date { get; set; }
        public string Payment_Type { get; set; }
        public string cardnumber { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRequestDetail> CustomerRequestDetails { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
