//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public string Transaction_ID { get; set; }
        public string Product_ID { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TransactionHeader TransactionHeader { get; set; }
    }
}
