//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public string Voucher_Code { get; set; }
        public int Amount { get; set; }
        public string Status { get; set; }
        public string Claimed_By { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
